#!/bin/bash
# Stack Detector — Code Anatomist v2.0.0
# Detects tech stack from source directory manifests
# Usage: ./stack-detector.sh <source-path> <output-path>

SOURCE_PATH="${1:-.}"
OUTPUT_PATH="${2:-stack-detection.yaml}"

echo "# Stack Detection Report" > "$OUTPUT_PATH"
echo "# Generated by: code-anatomist stack-detector v2.0.0" >> "$OUTPUT_PATH"
echo "# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OUTPUT_PATH"
echo "# Source: $SOURCE_PATH" >> "$OUTPUT_PATH"
echo "" >> "$OUTPUT_PATH"
echo "stack_detection:" >> "$OUTPUT_PATH"
echo "  source_path: \"$SOURCE_PATH\"" >> "$OUTPUT_PATH"

# Language detection
echo "  languages:" >> "$OUTPUT_PATH"

if [ -f "$SOURCE_PATH/package.json" ]; then
  echo "    - javascript_typescript" >> "$OUTPUT_PATH"
fi
if [ -f "$SOURCE_PATH/requirements.txt" ] || [ -f "$SOURCE_PATH/pyproject.toml" ] || [ -f "$SOURCE_PATH/setup.py" ]; then
  echo "    - python" >> "$OUTPUT_PATH"
fi
if [ -f "$SOURCE_PATH/go.mod" ]; then
  echo "    - go" >> "$OUTPUT_PATH"
fi
if [ -f "$SOURCE_PATH/Cargo.toml" ]; then
  echo "    - rust" >> "$OUTPUT_PATH"
fi
if [ -f "$SOURCE_PATH/pom.xml" ] || [ -f "$SOURCE_PATH/build.gradle" ] || [ -f "$SOURCE_PATH/build.gradle.kts" ]; then
  echo "    - java" >> "$OUTPUT_PATH"
fi
if ls "$SOURCE_PATH"/*.csproj 1>/dev/null 2>&1 || ls "$SOURCE_PATH"/*.sln 1>/dev/null 2>&1; then
  echo "    - dotnet" >> "$OUTPUT_PATH"
fi

# Database detection
echo "  database:" >> "$OUTPUT_PATH"

if [ -f "$SOURCE_PATH/prisma/schema.prisma" ]; then
  echo "    prisma: true" >> "$OUTPUT_PATH"
else
  echo "    prisma: false" >> "$OUTPUT_PATH"
fi

if [ -f "$SOURCE_PATH/docker-compose.yml" ] || [ -f "$SOURCE_PATH/docker-compose.yaml" ]; then
  if grep -q "postgres\|mysql\|mariadb\|mongo" "$SOURCE_PATH/docker-compose.yml" 2>/dev/null || \
     grep -q "postgres\|mysql\|mariadb\|mongo" "$SOURCE_PATH/docker-compose.yaml" 2>/dev/null; then
    echo "    docker_db: true" >> "$OUTPUT_PATH"
  else
    echo "    docker_db: false" >> "$OUTPUT_PATH"
  fi
else
  echo "    docker_db: false" >> "$OUTPUT_PATH"
fi

if find "$SOURCE_PATH" -maxdepth 3 -type d -name "migrations" 2>/dev/null | head -1 | grep -q .; then
  echo "    migrations: true" >> "$OUTPUT_PATH"
else
  echo "    migrations: false" >> "$OUTPUT_PATH"
fi

# Infrastructure detection
echo "  infrastructure:" >> "$OUTPUT_PATH"

if [ -f "$SOURCE_PATH/Dockerfile" ] || find "$SOURCE_PATH" -maxdepth 2 -name "Dockerfile" 2>/dev/null | head -1 | grep -q .; then
  echo "    docker: true" >> "$OUTPUT_PATH"
else
  echo "    docker: false" >> "$OUTPUT_PATH"
fi

if [ -f "$SOURCE_PATH/docker-compose.yml" ] || [ -f "$SOURCE_PATH/docker-compose.yaml" ]; then
  echo "    docker_compose: true" >> "$OUTPUT_PATH"
else
  echo "    docker_compose: false" >> "$OUTPUT_PATH"
fi

if [ -d "$SOURCE_PATH/.github/workflows" ]; then
  echo "    github_actions: true" >> "$OUTPUT_PATH"
else
  echo "    github_actions: false" >> "$OUTPUT_PATH"
fi

if [ -d "$SOURCE_PATH/terraform" ] || [ -f "$SOURCE_PATH/main.tf" ]; then
  echo "    terraform: true" >> "$OUTPUT_PATH"
else
  echo "    terraform: false" >> "$OUTPUT_PATH"
fi

# Tools recommendation
echo "  tools_available:" >> "$OUTPUT_PATH"

if [ -f "$SOURCE_PATH/package.json" ]; then
  echo "    - { name: dependency-cruiser, command: 'npx depcruise --output-type dot src', phase: 2 }" >> "$OUTPUT_PATH"
fi
if [ -f "$SOURCE_PATH/requirements.txt" ] || [ -f "$SOURCE_PATH/pyproject.toml" ]; then
  echo "    - { name: pydeps, command: 'pydeps --no-show src', phase: 2 }" >> "$OUTPUT_PATH"
fi
if [ -f "$SOURCE_PATH/prisma/schema.prisma" ]; then
  echo "    - { name: prisma-db-pull, command: 'npx prisma db pull', phase: 2 }" >> "$OUTPUT_PATH"
fi
echo "    - { name: mermaid, command: 'inline (text-based)', phase: '1,3,6,8' }" >> "$OUTPUT_PATH"

echo ""
echo "Stack detection complete: $OUTPUT_PATH"
